from __future__ import annotations

from pgvector.sqlalchemy import VECTOR
from sqlalchemy import ARRAY, Boolean, Column, DateTime, Float, ForeignKey, Integer, Table, Text, UniqueConstraint, func
from sqlalchemy.dialects.postgresql import JSONB, UUID

from ai_scientist.research_store.models import metadata


SCHEMA = "literature"


def _id(name: str) -> Column:
    return Column(name, UUID(as_uuid=False), primary_key=True)


def _created() -> Column:
    return Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now())


venues = Table("venues", metadata, _id("venue_id"), Column("code", Text, nullable=False, unique=True), Column("name", Text, nullable=False), Column("field", Text), Column("policy", JSONB, nullable=False, server_default="{}"), _created(), schema=SCHEMA)
venue_editions = Table("venue_editions", metadata, _id("venue_edition_id"), Column("venue_id", UUID(as_uuid=False), ForeignKey("literature.venues.venue_id"), nullable=False), Column("event_year", Integer, nullable=False), Column("status", Text, nullable=False, server_default="PLANNED"), Column("include_tracks", JSONB, nullable=False, server_default="[]"), Column("exclude_tracks", JSONB, nullable=False, server_default="[]"), UniqueConstraint("venue_id", "event_year", name="uq_venue_year"), _created(), schema=SCHEMA)
papers = Table("papers", metadata, _id("paper_id"), Column("title", Text, nullable=False), Column("normalized_title", Text, nullable=False), Column("abstract", Text, nullable=False, server_default=""), Column("publication_year", Integer), Column("status", Text, nullable=False, server_default="ACTIVE"), _created(), Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()), schema=SCHEMA)
paper_appearances = Table("paper_appearances", metadata, _id("paper_appearance_id"), Column("paper_id", UUID(as_uuid=False), ForeignKey("literature.papers.paper_id"), nullable=False), Column("venue_edition_id", UUID(as_uuid=False), ForeignKey("literature.venue_editions.venue_edition_id"), nullable=False), Column("track", Text, nullable=False), Column("acceptance_status", Text, nullable=False), Column("is_core_accepted", Boolean, nullable=False, server_default="false"), Column("official_source_url", Text, nullable=False), UniqueConstraint("paper_id", "venue_edition_id", "track", name="uq_paper_appearance"), _created(), schema=SCHEMA)
paper_identifiers = Table("paper_identifiers", metadata, _id("paper_identifier_id"), Column("paper_id", UUID(as_uuid=False), ForeignKey("literature.papers.paper_id"), nullable=False), Column("identifier_type", Text, nullable=False), Column("identifier_value", Text, nullable=False), UniqueConstraint("identifier_type", "identifier_value", name="uq_paper_identifier"), _created(), schema=SCHEMA)
paper_versions = Table("paper_versions", metadata, _id("paper_version_id"), Column("paper_id", UUID(as_uuid=False), ForeignKey("literature.papers.paper_id"), nullable=False), Column("version_label", Text, nullable=False), Column("source_url", Text, nullable=False), Column("content_hash", Text, nullable=False), Column("published_at", DateTime(timezone=True)), UniqueConstraint("paper_id", "version_label", "content_hash", name="uq_paper_version"), _created(), schema=SCHEMA)
authors = Table("authors", metadata, _id("author_id"), Column("name", Text, nullable=False), Column("normalized_name", Text, nullable=False, unique=True), _created(), schema=SCHEMA)
author_identifiers = Table("author_identifiers", metadata, _id("author_identifier_id"), Column("author_id", UUID(as_uuid=False), ForeignKey("literature.authors.author_id"), nullable=False), Column("identifier_type", Text, nullable=False), Column("identifier_value", Text, nullable=False), UniqueConstraint("identifier_type", "identifier_value", name="uq_author_identifier"), schema=SCHEMA)
paper_authors = Table("paper_authors", metadata, Column("paper_id", UUID(as_uuid=False), ForeignKey("literature.papers.paper_id"), primary_key=True), Column("author_id", UUID(as_uuid=False), ForeignKey("literature.authors.author_id"), primary_key=True), Column("position", Integer, nullable=False), Column("is_corresponding", Boolean, nullable=False, server_default="false"), schema=SCHEMA)
citations = Table("citations", metadata, _id("citation_id"), Column("citing_paper_id", UUID(as_uuid=False), ForeignKey("literature.papers.paper_id"), nullable=False), Column("cited_paper_id", UUID(as_uuid=False), ForeignKey("literature.papers.paper_id"), nullable=False), UniqueConstraint("citing_paper_id", "cited_paper_id", name="uq_citation_edge"), _created(), schema=SCHEMA)
citation_sources = Table("citation_sources", metadata, _id("citation_source_id"), Column("citation_id", UUID(as_uuid=False), ForeignKey("literature.citations.citation_id"), nullable=False), Column("source", Text, nullable=False), Column("source_record_id", Text, nullable=False), UniqueConstraint("citation_id", "source", "source_record_id", name="uq_citation_source"), _created(), schema=SCHEMA)
topics = Table("topics", metadata, _id("topic_id"), Column("name", Text, nullable=False, unique=True), Column("description", Text), schema=SCHEMA)
paper_topics = Table("paper_topics", metadata, Column("paper_id", UUID(as_uuid=False), ForeignKey("literature.papers.paper_id"), primary_key=True), Column("topic_id", UUID(as_uuid=False), ForeignKey("literature.topics.topic_id"), primary_key=True), Column("score", Float), schema=SCHEMA)
artifacts = Table("artifacts", metadata, _id("literature_artifact_id"), Column("paper_version_id", UUID(as_uuid=False), ForeignKey("literature.paper_versions.paper_version_id"), nullable=False), Column("uri", Text, nullable=False), Column("sha256", Text, nullable=False), Column("source_url", Text, nullable=False), Column("license", Text), Column("mime_type", Text), UniqueConstraint("paper_version_id", "sha256", name="uq_literature_artifact"), _created(), schema=SCHEMA)
documents = Table("documents", metadata, _id("document_id"), Column("paper_version_id", UUID(as_uuid=False), ForeignKey("literature.paper_versions.paper_version_id"), nullable=False), Column("literature_artifact_id", UUID(as_uuid=False), ForeignKey("literature.artifacts.literature_artifact_id"), nullable=False), Column("content_hash", Text, nullable=False), Column("parser_version", Text, nullable=False), UniqueConstraint("paper_version_id", "content_hash", name="uq_document_content"), _created(), schema=SCHEMA)
sections = Table("sections", metadata, _id("section_id"), Column("document_id", UUID(as_uuid=False), ForeignKey("literature.documents.document_id"), nullable=False), Column("section_type", Text, nullable=False), Column("heading", Text), Column("ordinal", Integer, nullable=False), Column("page_start", Integer), Column("page_end", Integer), Column("char_start", Integer, nullable=False), Column("char_end", Integer, nullable=False), Column("content_hash", Text, nullable=False), schema=SCHEMA)
chunks = Table("chunks", metadata, _id("chunk_id"), Column("document_id", UUID(as_uuid=False), ForeignKey("literature.documents.document_id"), nullable=False), Column("section_id", UUID(as_uuid=False), ForeignKey("literature.sections.section_id"), nullable=False), Column("paper_version_id", UUID(as_uuid=False), ForeignKey("literature.paper_versions.paper_version_id"), nullable=False), Column("ordinal", Integer, nullable=False), Column("content", Text, nullable=False), Column("token_count", Integer, nullable=False), Column("page_start", Integer), Column("page_end", Integer), Column("char_start", Integer, nullable=False), Column("char_end", Integer, nullable=False), Column("content_hash", Text, nullable=False), UniqueConstraint("document_id", "ordinal", "content_hash", name="uq_document_chunk"), schema=SCHEMA)
embedding_models = Table("embedding_models", metadata, _id("embedding_model_id"), Column("model_name", Text, nullable=False), Column("dimension", Integer, nullable=False), Column("config", JSONB, nullable=False), Column("config_hash", Text, nullable=False), UniqueConstraint("model_name", "config_hash", name="uq_embedding_model"), _created(), schema=SCHEMA)
embeddings = Table("embeddings", metadata, _id("embedding_id"), Column("chunk_id", UUID(as_uuid=False), ForeignKey("literature.chunks.chunk_id"), nullable=False), Column("embedding_model_id", UUID(as_uuid=False), ForeignKey("literature.embedding_models.embedding_model_id"), nullable=False), Column("content_hash", Text, nullable=False), Column("embedding", VECTOR(1024), nullable=False), UniqueConstraint("chunk_id", "embedding_model_id", "content_hash", name="uq_chunk_embedding"), _created(), schema=SCHEMA)
paper_notes = Table("paper_notes", metadata, _id("paper_note_id"), Column("paper_id", UUID(as_uuid=False), ForeignKey("literature.papers.paper_id"), nullable=False), Column("note_type", Text, nullable=False), Column("content", Text, nullable=False), Column("created_by_role", Text, nullable=False), _created(), schema=SCHEMA)
paper_claims = Table("paper_claims", metadata, _id("paper_claim_id"), Column("paper_version_id", UUID(as_uuid=False), ForeignKey("literature.paper_versions.paper_version_id"), nullable=False), Column("source_chunk_id", UUID(as_uuid=False), ForeignKey("literature.chunks.chunk_id"), nullable=False), Column("claim_type", Text, nullable=False), Column("claim_text", Text, nullable=False), Column("review_status", Text, nullable=False, server_default="unverified"), _created(), schema=SCHEMA)
paper_claim_evidence = Table("paper_claim_evidence", metadata, _id("paper_claim_evidence_id"), Column("paper_claim_id", UUID(as_uuid=False), ForeignKey("literature.paper_claims.paper_claim_id"), nullable=False), Column("source_chunk_id", UUID(as_uuid=False), ForeignKey("literature.chunks.chunk_id"), nullable=False), Column("relation", Text, nullable=False), UniqueConstraint("paper_claim_id", "source_chunk_id", "relation", name="uq_paper_claim_evidence"), schema=SCHEMA)
idea_paper_relations = Table("idea_paper_relations", metadata, _id("idea_paper_relation_id"), Column("idea_ref", Text, nullable=False), Column("paper_id", UUID(as_uuid=False), ForeignKey("literature.papers.paper_id"), nullable=False), Column("relation", Text, nullable=False), Column("retrieval_run_id", UUID(as_uuid=False), nullable=False), UniqueConstraint("idea_ref", "paper_id", "relation", "retrieval_run_id", name="uq_idea_paper_relation"), _created(), schema=SCHEMA)
retrieval_runs = Table("retrieval_runs", metadata, _id("retrieval_run_id"), Column("idea_ref", Text), Column("actor_role", Text, nullable=False), Column("query", Text, nullable=False), Column("query_variants", JSONB, nullable=False), Column("filters", JSONB, nullable=False), Column("retrieval_config", JSONB, nullable=False), Column("embedding_model", Text), Column("candidate_count", Integer, nullable=False, server_default="0"), Column("deep_read_set", JSONB, nullable=False, server_default="[]"), Column("status", Text, nullable=False, server_default="COMPLETE"), _created(), schema=SCHEMA)
retrieval_results = Table("retrieval_results", metadata, _id("retrieval_result_id"), Column("retrieval_run_id", UUID(as_uuid=False), ForeignKey("literature.retrieval_runs.retrieval_run_id"), nullable=False), Column("paper_id", UUID(as_uuid=False), ForeignKey("literature.papers.paper_id"), nullable=False), Column("rank", Integer, nullable=False), Column("score", Float, nullable=False), Column("keyword_rank", Integer), Column("dense_rank", Integer), Column("source_chunk_ids", ARRAY(UUID(as_uuid=False)), nullable=False, server_default="{}"), UniqueConstraint("retrieval_run_id", "paper_id", name="uq_retrieval_result"), schema=SCHEMA)
source_records = Table("source_records", metadata, _id("source_record_id"), Column("source", Text, nullable=False), Column("native_id", Text, nullable=False), Column("paper_id", UUID(as_uuid=False), ForeignKey("literature.papers.paper_id"), nullable=False), Column("raw_payload", JSONB, nullable=False), Column("payload_hash", Text, nullable=False), UniqueConstraint("source", "native_id", name="uq_source_native"), _created(), schema=SCHEMA)
ingestion_runs = Table("ingestion_runs", metadata, _id("ingestion_run_id"), Column("job_type", Text, nullable=False), Column("idempotency_key", Text, nullable=False, unique=True), Column("status", Text, nullable=False), Column("cursor", JSONB, nullable=False, server_default="{}"), Column("counts", JSONB, nullable=False, server_default="{}"), _created(), Column("completed_at", DateTime(timezone=True)), schema=SCHEMA)
sync_state = Table("sync_state", metadata, _id("sync_state_id"), Column("source", Text, nullable=False), Column("scope", Text, nullable=False), Column("cursor", JSONB, nullable=False), Column("last_success_at", DateTime(timezone=True)), UniqueConstraint("source", "scope", name="uq_sync_source_scope"), schema=SCHEMA)
merge_events = Table("merge_events", metadata, _id("merge_event_id"), Column("candidate_paper_id", UUID(as_uuid=False), ForeignKey("literature.papers.paper_id"), nullable=False), Column("existing_paper_id", UUID(as_uuid=False), ForeignKey("literature.papers.paper_id"), nullable=False), Column("reason", Text, nullable=False), Column("similarity", Float), Column("status", Text, nullable=False, server_default="CANDIDATE"), _created(), schema=SCHEMA)


TABLES = {table.name: table for table in metadata.tables.values() if table.schema == SCHEMA}
